### ISSUE TITLE
Path does not point to a valid file: helpers\buttons_xxx.js

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Tools-SMP#5] opened 2022-01-19 20:19 UTC
With the latest beta, I've unzipped the contents of the zip file to:
**W:\Apps (Portable)\Music Apps\foobar2000\profile\scripts\SMP\xxx-scripts**

I get this error when I load the **buttons_toolbar.js**
```
Error: Spider Monkey Panel v1.6.1 (Playlist Tools Menu)
include failed:
Path does not point to a valid file: helpers\buttons_xxx.js

File: <main>
Line: 40, Column: 3
Stack trace:
  @:40:3
```

I'm using a portable build.

EDIT
If I edit the **buttons_toolbar.js** file to the direct path it works.

It does have these errors though.
```
Buttons bar file not found:
W:\Apps (Portable)\Music Apps\foobar2000\profile\js_data\buttons_6iFiq.json
```

```
Buttons bar file not found:
W:\Apps (Portable)\Music Apps\foobar2000\profile\js_data\buttons_3rXJZ.json
```

```
Buttons bar file not found:
W:\Apps (Portable)\Music Apps\foobar2000\profile\js_data\buttons_iddIw.json
```

**Comment by regorxxx** [comment] 2022-01-20 10:14
If you read the release page, there is a warning about it:
https://github.com/regorxxx/Playlist-Tools-SMP/releases/tag/v3.0.0-beta.2

And also a fix. Apply it and let me know if it works (supposing you have installed it right obviously.).

If it does, then it's a bug on Spider Monkey panel, please report it there:
https://hydrogenaud.io/index.php?topic=116669.1100

**Comment by regorxxx** [comment] 2022-01-20 11:00
> ...
>  SMP 1.5.2 BUG: 
> -------------
> After properly installing the files, if Foobar2000 SMP panels keep crashing due to 'missing files', check '_switchPaths.zip'.
> Follow its instructions to fix it. Then report it at https://hydrogenaud.io/index.php?topic=116669.0 and hopefully it will be fixed.
> ...

**Comment by stephen147** [comment] 2022-01-20 19:06
Thanks, sorry for missing out on that. That fixed the issue.

Is it something regarding the relative paths that can get fix your end or is that got to do with SM?

**Comment by regorxxx** [comment] 2022-01-20 19:10
Don't think I can do anything more than providing that CMD script to use absolute paths... relative paths work for some people and not for others (it works on my side), and I have simply followed SMP specification... it has been that way since a few releases ago, so I would say it should be fixed by @TheQwertiest.

**Comment by stephen147** [comment] 2022-01-21 21:07
I've tried the batch file and it didn't work. I tried it twice.

Here's the output code:
```
Changing all relative paths to absolute paths on include functions.
Do you want to continue? Can't be reverted. [Y,N]?Y
---------------------------------------------------
Root
---------------------------------------------------
Replaced 0 occurence(s) in 0 file(s).
Replaced 0 occurence(s) in 0 file(s).
Replaced 0 occurence(s) in 0 file(s).
---------------------------------------------------
Helpers
---------------------------------------------------
Replaced 0 occurence(s) in 0 file(s).
Replaced 0 occurence(s) in 0 file(s).
---------------------------------------------------
Main
---------------------------------------------------
Replaced 0 occurence(s) in 0 file(s).
---------------------------------------------------
Buttons and toolbars
---------------------------------------------------
Replaced 0 occurence(s) in 0 file(s).
Replaced 0 occurence(s) in 0 file(s).
Replaced 0 occurence(s) in 0 file(s).
Replaced 0 occurence(s) in 0 file(s).

Done.
Press any key to continue . . .
```
I redownloaded the zip file and loaded the js file and then tried to check the logging checkbox for filein() in the advanced preferences in foobar and it immediately crashes the program. And it doesn't even attempt to start up again.. Luckily I have foo_jesus and restored it. I tried again a second time and the same thing.

So it appears I can't do any bug reporting for this.

**Comment by regorxxx** [comment] 2022-01-22 10:23
I have enabled it on my installation without problems. Did you enable it before or after reinstalling the scripts (with relative paths)?

Maybe you could try with a new clean portable install, so it doesn't break your working instance. Just a new portable installation, install SMP 1.6.1, enable the advanced debug option, restart it and then try installing the scripts there.

**Comment by stephen147** [comment] 2022-01-22 13:05
On my fresh install it worked bar not finding one json file.

That was
```
Buttons bar file not found:
 C:\Users\stevehero\Desktop\foobar2000\profile\js_data\buttons_EKIZK.json
```

The problem install is on a mapped NAS drive and is mapped to the Z: drive. It has seemed to have worked with the C: drive OK.

Here's the full log
```
Spider Monkey Panel v1.6.1 ({FE20573F-D628-438A-BF18-1FE772EB6F77}): initialized in 1 ms
Buttons bar file not found:
 C:\Users\stevehero\Desktop\foobar2000\profile\js_data\buttons_EKIZK.json
cyclicTagsDescriptor - File loaded: C:\Users\stevehero\Desktop\foobar2000\profile\scripts\SMP\xxx-scripts\helpers\dyngenre_map_xxx.js
Search Same By Button loaded.
Missing font: FontAwesome
C:\Users\stevehero\Desktop\foobar2000\profile\scripts\SMP\xxx-scripts\buttons\buttons_remove_duplicates.js not loaded
Search by Distance Buttons loaded.
User's music_graph_descriptors - File loaded: C:\Users\stevehero\Desktop\foobar2000\profile\scripts\SMP\xxx-scripts\helpers\music_graph_descriptors_xxx_user.js
User's music_graph_descriptors has been loaded but it contains no changes... using only default one.
SearchByDistance: CRC mistmatch. Deleting old json cache.
Missing font: FontAwesome
Missing font: FontAwesome
Missing font: FontAwesome
Missing font: FontAwesome
Search by Distance (CUSTOM) Buttons loaded.
Missing font: FontAwesome
Playlist Tools Menu Button loaded.
Missing font: FontAwesome
Playlist Tools History Button loaded.
Missing font: FontAwesome
Spider Monkey Panel v1.6.1 (Playlist Tools: Buttons Bar: Playlist Tools: Buttons Bar v3.0.0 by XXX): initialized in 465 ms
Calculating graph links 0%.
Calculating graph links 50%.
SearchByDistance: Saving Cache.
cyclicTagsDescriptor - File loaded: C:\Users\stevehero\Desktop\foobar2000\profile\scripts\SMP\xxx-scripts\helpers\dyngenre_map_xxx.js
Search Same By Button loaded.
Missing font: FontAwesome
C:\Users\stevehero\Desktop\foobar2000\profile\scripts\SMP\xxx-scripts\buttons\buttons_remove_duplicates.js not loaded
Search by Distance Buttons loaded.
User's music_graph_descriptors - File loaded: C:\Users\stevehero\Desktop\foobar2000\profile\scripts\SMP\xxx-scripts\helpers\music_graph_descriptors_xxx_user.js
User's music_graph_descriptors has been loaded but it contains no changes... using only default one.
Missing font: FontAwesome
Missing font: FontAwesome
Missing font: FontAwesome
Missing font: FontAwesome
Search by Distance (CUSTOM) Buttons loaded.
Missing font: FontAwesome
Playlist Tools Menu Button loaded.
Missing font: FontAwesome
Playlist Tools History Button loaded.
Missing font: FontAwesome
Spider Monkey Panel v1.6.1 (Playlist Tools: Buttons Bar: Playlist Tools: Buttons Bar v3.0.0 by XXX): initialized in 266 ms
SearchByDistance: New Cache - cacheLink
SearchByDistance: New Cache - cacheLinkSet
Calculating graph links 0%.
Calculating graph links 50%.
SearchByDistance: New Cache - cacheLink
SearchByDistance: New Cache - cacheLinkSet
```

**Comment by stephen147** [comment] 2022-01-22 13:18
I noticed when I was copying over your zip contents to my c drive folder on the desktop there were no problems but when I copied the same to the path on my mapped NAS folder it give me this error.

The full path is
```
W:\Apps (Portable)\Music Apps\foobar2000\profile\scripts\SMP\xxx-scripts
```

![image](https://user-images.githubusercontent.com/14054664/150639988-b0c64e75-616a-44ee-b6c2-9780400bc1f1.png)

**Comment by stephen147** [comment] 2022-01-22 13:32
Sorry for spamming but I reinstalled the latest https://github.com/TheQwertiest/foo_spider_monkey_panel/releases which I already had done. I actually installed the debug version and loaded your js file and it seems to have loaded all correctly.

It's seems a similar log to that of the fresh install.

Here's the contents of that.

```
[13:28:25] Playlist Organizer: Last instance destroyed, Memorizing configuration
[13:28:27] JScript Panel v2.8.0.1 (Spectrogram Seekbar by marc2003): initialised in 27 ms
[13:28:27] JScript Panel v2.8.0.1 (Spectrogram Seekbar by marc2003): initialised in 16 ms
[13:28:28] Playlist view initialised in: 0.005 s
[13:28:28] JScript Panel v2.8.0.1 (id:591096): initialised in 10 ms
[13:28:28] Buttons bar file not found:
 W:\Apps (Portable)\Music Apps\foobar2000\profile\js_data\buttons_ciV9p.json
[13:28:28] cyclicTagsDescriptor - File loaded: W:\Apps (Portable)\Music Apps\foobar2000\profile\scripts\SMP\xxx-scripts\helpers\dyngenre_map_xxx.js
[13:28:28] Search Same By Button loaded.
[13:28:28] Missing font: FontAwesome
[13:28:28] W:\Apps (Portable)\Music Apps\foobar2000\profile\scripts\SMP\xxx-scripts\buttons\buttons_remove_duplicates.js not loaded
[13:28:28] Search by Distance Buttons loaded.
[13:28:28] User's music_graph_descriptors - File loaded: W:\Apps (Portable)\Music Apps\foobar2000\profile\scripts\SMP\xxx-scripts\helpers\music_graph_descriptors_xxx_user.js
[13:28:28] User's music_graph_descriptors has been loaded but it contains no changes... using only default one.
[13:28:28] SearchByDistance: CRC mistmatch. Deleting old json cache.
[13:28:28] Missing font: FontAwesome
[13:28:28] Missing font: FontAwesome
[13:28:28] Missing font: FontAwesome
[13:28:28] Missing font: FontAwesome
[13:28:28] Search by Distance (CUSTOM) Buttons loaded.
[13:28:28] Missing font: FontAwesome
[13:28:28] Playlist Tools Menu Button loaded.
[13:28:29] Missing font: FontAwesome
[13:28:29] Playlist Tools History Button loaded.
[13:28:29] Missing font: FontAwesome
[13:28:29] Spider Monkey Panel v1.6.1 (Debug) (Playlist Tools: Buttons Bar: Playlist Tools: Buttons Bar v3.0.0 by XXX): initialized in 900 ms
[13:28:29] Album list panel: initialised in 0.169 s
[13:28:29] Album list panel: initialised in 0.328 s
[13:28:29] Album list panel: initialised in 0.211 s
[13:28:30] Album list panel: initialised in 0.100 s
[13:28:30] Album list panel: initialised in 0.088 s
[13:28:30] HDD wakeup - touching file: Z:\{A53AE67A-5343-4E7C-9C19-63BC430EA8C7}
[13:28:30] HDD wakeup - touched file: Z:\{A53AE67A-5343-4E7C-9C19-63BC430EA8C7}
[13:28:31] Calculating graph links 0%.
[13:28:31] Calculating graph links 25%.
[13:28:32] Calculating graph links 50%.
[13:28:32] Calculating graph links 75%.
[13:28:33] Calculating graph links 100%.
[13:28:33] SearchByDistance: New Cache - cacheLink
[13:28:33] SearchByDistance: New Cache - cacheLinkSet
[13:29:00] Autobackup: Backed up 4119 items to autobackup.20220122-132823.zip
```

**Comment by regorxxx** [comment] 2022-01-24 23:11
The copy error is a windows thing not related at all to the scripts... so sorry but cant help with that. Don't even know why you have symlinks (?)

The font thing is your fault, it's a requisite on the installation instructions :)

The missing json file, I don't understand your problem. In fact the scripts should not work as intended if the json file is not found XD It points to the buttons bar, so if foobar doesn't load the previous file, any modification will be reset on restart.
Does the file exist? Did you clear the properties of the panel? Need more info about those missing files, since that's not what should be happening. 

I understand the installation error has been gone (?) but I don't get why since you have reinstalled SMP and the scripts and nothing more (?)

**Comment by regorxxx** [comment] 2022-01-24 23:15
I need:
- Screenshot of the properties panel for the panel which gives error.
- Screenshot of the folder " W:\Apps (Portable)\Music Apps\foobar2000\profile\js_data"
- Logs after starting foobar (now that it has been already installed).

Also... are you saying the debug version works but the regular one doesn't? (with all the other variables being the same) If that's the case then you are reporting an SMP bug.

**Comment by stephen147** [comment] 2022-01-25 20:29
1. I can't really leave a screenshot of the panel as it's working now and it takes a fair bit of time to setup up.

2. Here's the folder screenshot:
![image](https://user-images.githubusercontent.com/14054664/151053899-33eecb23-c976-4bd6-a5ad-4bb78ee0fdb6.png)

3. Here's the log after a minute after initial startup.

```
[20:26:05] "Key: 06B" : 0:00.061326
[20:26:05] "Key: 07A" : 0:00.065296
[20:26:05] "Key: 07B" : 0:00.061654
[20:26:05] "Key: 08A" : 0:00.067916
[20:26:05] "Key: 08B" : 0:00.060799
[20:26:05] "Key: 09A" : 0:00.066662
[20:26:05] "Key: 09B" : 0:00.062927
[20:26:05] "Key: 10A" : 0:00.063384
[20:26:05] "Key: 10B" : 0:00.060957
[20:26:05] "Key: 11A" : 0:00.064949
[20:26:05] "Key: 11B" : 0:00.061757
[20:26:05] "Key: 12A" : 0:00.060934
[20:26:05] "Key: 12B" : 0:00.060846
[20:26:05] "Keys: ALL" : 0:00.061001
[20:26:05] "Playcount > 15" : 0:00.086832
[20:26:05] "Played History" : 0:00.088341
[20:26:05] "Playlist: Not Released + Set Rips" : 0:00.098989
[20:26:05] "RLabel: Bpitch Control" : 0:00.059397
[20:26:05] "RLabel: Circus" : 0:00.060260
[20:26:05] "RLabel: Cocoon" : 0:00.059744
[20:26:05] "RLabel: Confession" : 0:00.059666
[20:26:05] "RLabel: Diynamic" : 0:00.060848
[20:26:05] "RLabel: Drumcode" : 0:00.060751
[20:26:05] "RLabel: Ellum" : 0:00.061145
[20:26:05] "RLabel: Freerange Records" : 0:00.058861
[20:26:05] "RLabel: Herzblut" : 0:00.059647
[20:26:05] "RLabel: Hungry Music" : 0:00.059641
[20:26:05] "RLabel: Innervisions" : 0:00.059849
[20:26:05] "RLabel: Involve" : 0:00.061053
[20:26:05] "RLabel: Mobilee" : 0:00.059236
[20:26:05] "RLabel: PRMD" : 0:00.060348
[20:26:05] "RLabel: Regal" : 0:00.059994
[20:26:05] "RLabel: SCI+TEC" : 0:00.059801
[20:26:05] "RLabel: Size" : 0:00.060435
[20:26:05] "RLabel: Soma" : 0:00.058890
[20:26:05] "RLabel: Sosumi" : 0:00.059109
[20:26:05] "RLabel: Southern Fried Records" : 0:00.059940
[20:26:05] "RLabel: Spinnin" : 0:00.061100
[20:26:05] "RLabel: Spinnin Deep" : 0:00.062112
[20:26:05] "RLabel: Toolroom" : 0:00.059158
[20:26:05] "RLabel: Touched." : 0:00.061114
[20:26:05] "RLabel: ZYX Music" : 0:00.059752
[20:26:05] "RLabel: _None" : 0:00.060866
[20:26:05] "RLabel: mau5trap" : 0:00.059251
[20:26:05] "Ratings & NRG: All - NRG 01-03" : 0:00.061127
[20:26:05] "Ratings & NRG: All - NRG 04-06" : 0:00.066183
[20:26:05] "Ratings & NRG: All - NRG 07" : 0:00.062328
[20:26:05] "Ratings & NRG: All - NRG 08" : 0:00.062065
[20:26:05] "Ratings & NRG: All - NRG 09" : 0:00.060562
[20:26:05] "Ratings & NRG: All - NRG 10" : 0:00.060826
[20:26:05] "Ratings & NRG: All - ★" : 0:00.060697
[20:26:05] "Ratings & NRG: All - ★'s 4-7" : 0:00.066447
[20:26:05] "Ratings & NRG: All - ★'s 5-7" : 0:00.065686
[20:26:05] "Ratings & NRG: All - ★'s 6-7" : 0:00.064507
[20:26:05] "Ratings & NRG: All - ★★" : 0:00.061424
[20:26:05] "Ratings & NRG: All - ★★★" : 0:00.061878
[20:26:05] "Ratings & NRG: All - ★★★★" : 0:00.061788
[20:26:05] "Ratings & NRG: All - ★★★★★" : 0:00.062533
[20:26:05] "Ratings & NRG: All - ★★★★★★" : 0:00.063389
[20:26:05] "Ratings & NRG: All - ★★★★★★★" : 0:00.063307
[20:26:05] "Ratings & NRG: Electronic - NRG 01-03" : 0:00.062425
[20:26:05] "Ratings & NRG: Electronic - NRG 04-06" : 0:00.082743
[20:26:05] "Ratings & NRG: Electronic - NRG 07" : 0:00.070665
[20:26:05] "Ratings & NRG: Electronic - NRG 08" : 0:00.065463
[20:26:05] "Ratings & NRG: Electronic - NRG 09" : 0:00.060462
[20:26:05] "Ratings & NRG: Electronic - NRG 10" : 0:00.061070
[20:26:05] "Ratings & NRG: Electronic - ★" : 0:00.061723
[20:26:05] "Ratings & NRG: Electronic - ★'s  4-7" : 0:00.095200
[20:26:05] "Ratings & NRG: Electronic - ★'s 5-7" : 0:00.088066
[20:26:05] "Ratings & NRG: Electronic - ★'s 6-7" : 0:00.078009
[20:26:05] "Ratings & NRG: Electronic - ★★" : 0:00.062927
[20:26:05] "Ratings & NRG: Electronic - ★★★" : 0:00.063652
[20:26:05] "Ratings & NRG: Electronic - ★★★★" : 0:00.066799
[20:26:05] "Ratings & NRG: Electronic - ★★★★★" : 0:00.074846
[20:26:05] "Ratings & NRG: Electronic - ★★★★★★" : 0:00.071663
[20:26:05] "Ratings & NRG: Electronic - ★★★★★★★" : 0:00.066378
[20:26:05] "Shower Music" : 0:00.031930
[20:26:05] "_All Music" : 0:00.068893
[20:26:05] "_Better: CDs without LOGS" : 0:00.105462
[20:26:05] "_Check: %ENCODED BY% HAS "Lame" AND (%CODEC% HAS FLAC OR %MEDIATYPE% HAS "kbps")" : 0:00.071097
[20:26:05] "_Check: 1. To Rate" : 0:00.059991
[20:26:05] "_Check: 2. MEDIATYPE_ORIGINAL MISSING" : 0:00.082288
[20:26:05] "_Check: 3. TRACKNUNMBER OR TOTALTRACKS with 0" : 0:00.092111
[20:26:05] "_Check: 4a. KEY to Do" : 0:00.133173
[20:26:05] "_Check: 4b. KEY Check" : 0:00.108551
[20:26:05] "_Check: 4c. KEY 0's" : 0:00.191740
[20:26:05] "_Check: 4d. KEY ALL Value" : 0:00.097624
[20:26:05] "_Check: 4d. KEY Title Wrong" : 0:00.435459
[20:26:05] "_Check: 5. COMPOSER undefined" : 0:00.028660
[20:26:05] "_Check: 6. Traktor - DESCRIPTION PRESENT" : 0:00.059909
[20:26:05] "_Check: 6. Traktor - KEY - INITIAL KEY for MP3" : 0:00.072999
[20:26:05] "_Check: 6. Traktor - KEY - INITIALKEY for FLAC" : 0:00.081840
[20:26:05] "_Check: 6. Traktor - MIXARTIST - MIXARTIST for FLAC" : 0:00.085984
[20:26:05] "_Check: 6. Traktor - MIXARTIST - REMIXED BY for MP3" : 0:00.074974
[20:26:05] "_Check: 6. Traktor - RATING WMP for FLAC (Values: 51, 102, 153, 204, 255)" : 0:00.086877
[20:26:05] "_Check: 6. Traktor - RATING for MP3 (Values 1, 2, 3, 4, 5)" : 0:00.071631
[20:26:05] "_Check: 6: Traktor - TRAKTOR4 PRESENT" : 0:00.029276
[20:26:05] "_Check: 7. ITUNESCOMPILATION MISSING OR COMPILATION PRESENT" : 0:00.143806
[20:26:05] "_Check: ADDED_TIMESTAMP MISSING" : 0:00.060444
[20:26:05] "_Check: ALBUMARTIST" : 0:00.095015
[20:26:05] "_Check: ALBUMARTISTSORT PRESENT" : 0:00.029651
[20:26:05] "_Check: ALL HAS "beatport" AND %directory% HAS "CD,"" : 0:00.050885
[20:26:05] "_Check: ARTISTS PRESENT" : 0:00.029549
[20:26:05] "_Check: BAD ID3's" : 0:00.058064
[20:26:05] "_Check: BAND PRESENT" : 0:00.028587
[20:26:05] "_Check: BEATPORT_ITEM_TYPE PRESENT AND WWW HAS "discogs"" : 0:00.053191
[20:26:05] "_Check: CATALOG # <<< %CAT% %CATALOG#% %CATALOG% %CATALOGID% %CATALOGNUMBER% %CATALOGUENUMBER% %LABELNO%" : 0:00.070770
[20:26:05] "_Check: COMENTS" : 0:00.028290
[20:26:05] "_Check: COMMENT has correct key" : 0:00.061309
[20:26:05] "_Check: COMPOSERSORT" : 0:00.027850
[20:26:05] "_Check: CONTACT" : 0:00.027965
[20:26:05] "_Check: COUNTRY <<< DISCOGS_COUNTRY PRESENT" : 0:00.030241
[20:26:05] "_Check: DATE MISSING" : 0:00.059190
[20:26:05] "_Check: DATE Meta > 1" : 0:00.095473
[20:26:05] "_Check: DEEZER Fix Tags" : 0:00.068506
[20:26:05] "_Check: DISCNUMBER" : 0:00.060752
[20:26:05] "_Check: DISCOGS_MASTER_RELEASE_ID <<< %DISCOGS_MASTER_ID% PRESENT" : 0:00.061513
[20:26:05] "_Check: DISCOGS_RELEASE_ID PRESENT AND %www% HAS "beatport"" : 0:00.074773
[20:26:05] "_Check: DISCOGS_RELEASE_MONTH PRESENT OR DISCOGS_RELEASE_MONTH PRESENT" : 0:00.031555
[20:26:05] "_Check: DISPLAY ARTIST" : 0:00.029073
[20:26:05] "_Check: DYNAMIC RANGE PRESENT" : 0:00.028454
[20:26:05] "_Check: Discogs Crap - %DISCOGS_ALBUM_RELEASECOUNTRY% %DISCOGS_ALBUMARTIST_URL% %DISCOGS_ARTIST_LINK% %DISCOGS_ARTIST_LIST% %DIS" : 0:00.085649
[20:26:05] "_Check: EDITION PRESENT" : 0:00.028689
[20:26:05] "_Check: ENCODED BY <<< %ENCODEDBY% %ENCODER% %ENCODER+% %RIPPING TOOL%" : 0:00.065524
[20:26:05] "_Check: ENCODER SETTINGS <<< %ENCODING SETTINGS% %RIPPING_NOTES" : 0:00.063972
[20:26:05] "_Check: EXPLICIT (Is not 0 or 1)" : 0:00.030172
[20:26:05] "_Check: FEATURED, FEATURING PRESENT" : 0:00.064928
[20:26:05] "_Check: GENRESORT PRESENT" : 0:00.029486
[20:26:05] "_Check: GROUPING PRESENT" : 0:00.059760
[20:26:05] "_Check: GROUPING PRESENT (Double Check)" : 0:00.064541
[20:26:05] "_Check: GUEST ARTIST PRESENT <<< Add to TITLE with feat. GUEST ARTIST and remove" : 0:00.029678
[20:26:05] "_Check: Genre Without Style" : 0:00.076510
[20:26:05] "_Check: INVOLVED PEOPLE LIST <<< %INVOLVEDPEOPLE% %INVOLVEDPEOPLELIST% PRESENT" : 0:00.063194
[20:26:05] "_Check: ITUNES GROUPING PRESENT" : 0:00.059521
[20:26:05] "_Check: ITUNESADVISORY PRESENT" : 0:00.062102
[20:26:05] "_Check: ITUNES_CDDB_1 PRESENT" : 0:00.059049
[20:26:05] "_Check: ITUNNORM PRESENT" : 0:00.060014
[20:26:05] "_Check: LABEL PRESENT" : 0:00.028989
[20:26:05] "_Check: LENGTH OR DURATION PRESENT" : 0:00.028902
[20:26:05] "_Check: MEDIA TYPE <<< %MEDIATYPE% %RELEASE TYPE% %SOURCEMEDIA% %SOURCE MEDIA% PRESENT" : 0:00.066399
[20:26:05] "_Check: MEDIATYPE_ORIGINAL HAS "CD" AND NOT WWW HAS "discogs"" : 0:00.070105
[20:26:05] "_Check: MIXER PRESENT" : 0:00.058752
[20:26:05] "_Check: MOOD PRESENT" : 0:00.028478
[20:26:05] "_Check: NASTERID PRESENT" : 0:00.028564
[20:26:05] "_Check: NOTES PRESENT" : 0:00.028839
[20:26:05] "_Check: OFFICIAL AUDIO FILE WEBPAGE PRESENT" : 0:00.028701
[20:26:05] "_Check: OFFICIAL PUBLISHER WEBPAGE PRESENT" : 0:00.028440
[20:26:05] "_Check: ORIGINAL ALBUM/MOVIE/SHOW TITLE PRESENT" : 0:00.028736
[20:26:05] "_Check: ORIGINAL ARTIST(S)/PERFORMER(S) PRESENT" : 0:00.028476
[20:26:05] "_Check: ORIGINAL RELEASE YEAR <<< %DATE_ORIGINAL% %ORIGINAL RELEASE DATE% %ORIGINALDATE%" : 0:00.065387
[20:26:05] "_Check: Only id3v2.4 or id3v1" : 0:00.093291
[20:26:05] "_Check: PUBLISHERS Long" : 0:00.064776
[20:26:05] "_Check: RELEASE DATE PRESENT" : 0:00.059384
[20:26:05] "_Check: RELEASEDATE PRESENT" : 0:00.059708
[20:26:05] "_Check: RELEASETIME PRESENT" : 0:00.060467
[20:26:05] "_Check: REPLAYGAIN MISSING" : 0:00.060146
[20:26:05] "_Check: SCRIPT PRESENT" : 0:00.029946
[20:26:05] "_Check: STYLE MISSING" : 0:00.062086
[20:26:05] "_Check: SUBTITLE PRESENT" : 0:00.028447
[20:26:05] "_Check: TEMPO PRESENT" : 0:00.028639
[20:26:05] "_Check: TIME_CHECK PRESENT" : 0:00.029179
[20:26:05] "_Check: TOTALDISCS MISSING" : 0:00.030486
[20:26:05] "_Check: TOTALDISKS PRESENT" : 0:00.028900
[20:26:05] "_Check: TRACKURL PRESENT" : 0:00.028660
[20:26:05] "_Check: UNSYNCED LYRICS HAS eng|| or xxs||" : 0:00.036467
[20:26:05] "_Check: UNSYNCEDLYRICS PRESENT" : 0:00.059882
[20:26:05] "_Check: UPPER Extensions" : 0:00.097727
[20:26:05] "_Check: VERSION PRESENT" : 0:00.061163
[20:26:05] "_Check: VINYL _FILENAMES Don't have A, B, C etc." : 0:00.060178
[20:26:05] "_Check: WWW <<< %URL% %WEBSITE%" : 0:00.062285
[20:26:05] "_Check: Wrong Folder Check" : 0:00.131785
[20:26:05] "_Check: YEAR PRESENT" : 0:00.058902
[20:26:05] "_Check: YEARBACKUP PRESENT" : 0:00.061405
[20:26:05] "_Check: ‘ (Left Quote)" : 0:00.066586
[20:26:05] "_Check: ’ (Right Quote)" : 0:00.065412
[20:26:05] "_Codec Type: FLACs" : 0:00.063641
[20:26:05] "_Codec Type: MP3s" : 0:00.061718
[20:26:05] "_ID3 Type: id3v2.3|id3v1" : 0:00.061858
[20:26:05] "_ID3 Type: id3v2.4|id3v1" : 0:00.059581
[20:26:05] "_Location: Movie Themes for Kodi" : 0:00.062466
[20:26:05] "_Location: Z:\Music\_LOSSLESS" : 0:00.065836
[20:26:05] "_Location: Z:\Music\_LOSSY" : 0:00.064358
[20:26:05] "_Location: Z:\Music\_PODCASTS" : 0:00.061825
[20:26:05] "_Location: _Full Library" : 0:00.068075
[20:26:05] "_Standards: LESS 320kbps" : 0:00.060601
[20:26:05] "_Time: HOUR: 01" : 0:00.088129
[20:26:05] "_Time: WEEK: 0.1" : 0:00.086343
[20:26:05] "_Time: WEEK: 01" : 0:00.086483
[20:26:05] "_Time: WEEK: 02" : 0:00.085777
[20:26:05] "_Time: WEEK: 03" : 0:00.087053
[20:26:05] "_Time: WEEK: 04" : 0:00.086071
[20:26:05] "_Time: WEEK: 05-08" : 0:00.085492
[20:26:05] "_Time: WEEKS ALL: .1 - 04" : 0:00.086508
[20:26:05] "_Time: WEEKS ALL: .1 - 08" : 0:00.086174
[20:26:05] "_To Sort: Soundcloud Tracks" : 0:00.061122
[20:26:05] FFmpeg version: 4.3.1
[20:26:05] Startup time : 0:28.690836
[20:26:05] SearchByDistance: New Cache - cacheLinkSet
[20:27:16] Autobackup: Backed up 4295 items to autobackup.20220125-202641.zip
```

**Comment by regorxxx** [comment] 2022-01-26 00:47
There is no error on that log at all, and you have +10 buttons files there which are not needed at all due to wrong installations.
Btw the screenshot was of the panel properties, you don't have to reinstall or do anything for that. Neither loose the setup. 

I guess if you finally managed to do it right then.. is it solved?

**Comment by stephen147** [comment] 2022-01-26 19:50
> I guess if you finally managed to do it right then.. is it solved?

I guess so for now. I'll see how the next release of this goes.

I was going to ask how do I keep the settings when updating but that may be better to ask on a separate issue as a question?

**Comment by regorxxx** [comment] 2022-01-27 00:03
As long as you simply overwrite the old files with the new ones, all should be updated without problems -with previous settings- on next startup.

You don't have to reinstall anything, or clear the panel, or things like that. Anyway you can always export the properties, at the properties panel, to create backups of the config (which can be imported at a later point, or on other panels).

**Closed** 2022-01-27 00:08 UTC

**Comment by stephen147** [comment] 2022-01-27 00:09
Cool. Thanks for this great tool.
