### ISSUE TITLE
Playlist with ampersands not showing in playlist items

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Tools-SMP#3] opened 2021-06-23 22:28 UTC
I have a playlist named **LISTEN & RATE**.

It's displaying as:

![image](https://user-images.githubusercontent.com/14054664/123175979-983a7a80-d47a-11eb-892d-b7114521f34c.png)

**Comment by regorxxx** [comment] 2021-06-24 20:56
Can you point me to the place where you are seeing that? Menus?
& char will not be displayed in menus. That's a limitation of SMP, and can't do nothing about it.

In menus it should simply be skipped. In other places it makes next char to be underscored.

If it's a text displayed on panels or tooltips, it can be fixed.

**Comment by stephen147** [comment] 2021-06-24 21:04
Here's where it is:

![image](https://user-images.githubusercontent.com/14054664/123332100-fda07100-d537-11eb-89b1-d9e16188b92d.png)

**Comment by regorxxx** [comment] 2021-06-24 21:10
Nevermind, found the problem. & chars must be doubled to work as intended. Try it by yourself renaming your playlist with double &, and it should appear once on the menu.

Instead of editing Playlist Tools, I have edited the Menu Framework to replace by default all '&' with double &&. So it will work by default with arbitrary user input and I will not have to care anymore about it when writing new code. (in fact I didn't used that char on purpose on menus before).

**Comment by regorxxx** [comment] 2021-06-24 21:21
By the way, the problem on my side is & not showing at all. In your case & makes next char to be underscored, which is a behavior of [text drawing but not menus](https://theqwertiest.github.io/foo_spider_monkey_panel/assets/generated_files/docs/html/GdiGraphics.html#GdiDrawText). Check my proposed workaround works (just test it and revert the change), if it does, next release will fix it for you. Otherwise that would be a bug at other place (or SMP).

**Comment by stephen147** [comment] 2021-06-25 10:18
Doubling them up only resulted in the playlist name in fb having 2 ampersands which is to be expected but it did work to display correctly in your menus which means it can be fixed :)

![image](https://user-images.githubusercontent.com/14054664/123409677-5b6ba200-d5a6-11eb-8f60-47ae13e497d7.png)

**Comment by regorxxx** [comment] 2021-06-25 11:31
Great. Thanks. Will be fixed on next release then, will take some days since I'm fully working on integration with the online controller (foo http_control)  and some major changes for SMP main menus configuration which should allow foobar to be a direct replacement of other music servers too.

Btw, and not related in any way to that... is it comfortable to work with so many loaded playlists at the same time?
https://github.com/regorxxx/Playlist-Tools-SMP/issues/4

**Closed** 2021-08-11 18:23 UTC
Labels: bug, good first issue
